# Generated by Django 4.1.2 on 2023-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('utm_source', models.CharField(blank=True, max_length=50)),
                ('utm_medium', models.CharField(blank=True, max_length=50)),
                ('utm_campaign', models.CharField(blank=True, max_length=50)),
                ('clicks_remaining', models.IntegerField(default=1)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
