# Generated by Django 4.1.2 on 2023-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhasher', '0002_alter_url_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='clicks_remaining',
            field=models.IntegerField(default=100),
        ),
    ]
