# Generated by Django 4.1.2 on 2023-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhasher', '0004_urlshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='utm_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
