# Generated by Django 4.1.2 on 2023-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhasher', '0005_alter_url_long_url_alter_url_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='value',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
