# Generated by Django 4.1.2 on 2023-04-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlhasher', '0007_alter_urlshort_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='url_id', to='urlhasher.url'),
        ),
    ]
